CREATE TABLE nodes (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
uri VARCHAR(2048) NOT NULL,
dpub TIMESTAMP,
interactions TEXT CHARACTER SET utf8
);

CREATE TABLE links (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
source_node_uri VARCHAR(2048) NOT NULL,
target_node_uri VARCHAR(2048) NOT NULL,
interaction TEXT CHARACTER SET utf8,
root_node_uri VARCHAR(2048) NOT NULL
);

CREATE TABLE roots (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
root_node_uri VARCHAR(2048) NOT NULL,
interaction TEXT CHARACTER SET utf8
);

CREATE TABLE cascades (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
path_cnt BIGINT
);

CREATE TABLE nodes_cascades (
node_uri VARCHAR(2048) NOT NULL,
cascades_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY
);